version: '3'
services:
  app:
    build: .
    image: document-store-api:local
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:3.4.17
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
    command: mongod --smallfiles --logpath=/dev/null # --quiet