name    'ft-document_store_api'
version '@semver@'
source 'UNKNOWN'
author 'ft'
license 'Apache License, Version 2.0'
summary 'UNKNOWN'
description 'UNKNOWN'
project_page 'UNKNOWN'

## Add dependencies, if any:
dependency 'ft/content_runnablejar', '1.1.x'
dependency 'ft/content_platform_nagios', '2.x'
dependency 'ft/sudoers_sudocont', '>=0.0.1'
dependency 'ft/common_pp_up', '>=0.0.1' 
